import ast
import base64
import re
import urllib.parse
from functools import partial

from utils import Cache, Time, get_logger, leagues, network

log = get_logger(__name__)

urls: dict[str, dict[str, str | float]] = {}

TAG = "STRTP"

CACHE_FILE = Cache(TAG, exp=19_800)

API_FILE = Cache(f"{TAG}-api", exp=19_800)

# Try different possible API endpoints
API_ENDPOINTS = [
    "https://streamtpnew.com/eventos.json",
]

REFERER = "https://streamtpnew.com/"
ORIGIN = "https://streamtpnew.com/"

# User agents for different platforms
USER_AGENTS = {
    "vlc": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1",
    "tivimate": "Mozilla/5.0 (Linux; Android 7.1.2; ASUS_I003DD Build/N2G48H; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.193"
}


def convert_to_mono_stream(url: str) -> str:
    if not url or "index.m3u8" not in url:
        return url
    
    try:
        # Parse the URL
        parsed = urllib.parse.urlparse(url)
        
        # Extract path and query
        path = parsed.path
        query = parsed.query
        
        # Extract token from query
        token_match = re.search(r'token=([^&]+)', query)
        if not token_match:
            return remove_ip_param(url)
        
        original_token = token_match.group(1)
        
        # Parse token parts (format: hash-XX-timestamp1-timestamp2)
        token_parts = original_token.split('-')
        
        if len(token_parts) >= 4:
            # Extract the token parts
            hash_part = token_parts[0]
            middle_part = token_parts[1]
            timestamp1 = token_parts[2]
            timestamp2 = token_parts[3]
            
            # Map of token conversions (based on observed patterns)
            token_conversion_map = {
                '2f': 'b8',
                'b8': '2f',
                '3a': 'c9',
                'c9': '3a',
                '4d': 'e6',
                'e6': '4d',
                '5e': 'f7',
                'f7': '5e',
                '6b': '84',
                '84': '6b',
                '7c': '95',
                '95': '7c',
                '8a': 'd3',
                'd3': '8a',
                '9e': 'c1',
                'c1': '9e',
                'ad': 'b2',
                'b2': 'ad',
            }
            
            # Convert the middle part
            converted_middle = token_conversion_map.get(middle_part, middle_part)
            
            # For numeric parts, apply XOR transformation
            if converted_middle == middle_part and middle_part.isdigit():
                try:
                    num = int(middle_part)
                    converted_num = num ^ 0xFF
                    converted_middle = str(converted_num)
                except:
                    converted_middle = middle_part
            
            # Create new token with converted middle part
            new_token = f"{hash_part}-{converted_middle}-{timestamp1}-{timestamp2}"
            
            # Build new path
            path_parts = path.split('/')
            if len(path_parts) >= 2:
                path_parts[-1] = 'tracks-v1a1/mono.m3u8'
                new_path = '/'.join(path_parts)
            else:
                new_path = path.replace('index.m3u8', 'tracks-v1a1/mono.m3u8')
            
            # Create new query without ip parameter
            query_params = {}
            for param in query.split('&'):
                if '=' in param:
                    key, value = param.split('=', 1)
                    if key != 'ip':
                        query_params[key] = value
            
            # Update token in query params
            query_params['token'] = new_token
            
            # Build new query string
            new_query = '&'.join([f"{k}={v}" for k, v in query_params.items()])
            
            # Reconstruct URL
            new_url = urllib.parse.urlunparse((
                parsed.scheme,
                parsed.netloc,
                new_path,
                parsed.params,
                new_query,
                parsed.fragment
            ))
            
            log.debug(f"Token conversion: {middle_part} -> {converted_middle}")
            return new_url
            
    except Exception as e:
        log.debug(f"Error converting URL: {e}")
    
    return remove_ip_param(url)


def remove_ip_param(url: str) -> str:
    """Remove ip parameter from URL"""
    if '&ip=' in url:
        return url.split('&ip=')[0]
    elif '?ip=' in url:
        return url.split('?ip=')[0]
    return url


def generate_vlc_playlist(data: dict, output="strtp_vlc.m3u8") -> int:
    """Generate VLC-compatible playlist"""
    lines = ["#EXTM3U"]
    lines.append(f"# Playlist generated by STRTP updater - {Time.clean(Time.now()).strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")
    count = 0

    for key, entry in sorted(data.items()):
        url = entry.get("url")
        if not url:
            continue

        tvg_id = entry.get("id", "Live.Event.us")
        tvg_logo = entry.get("logo", "https://i.gyazo.com/4a5e9fa2525808ee4b65002b56d3450e.png")
        group_title = entry.get("sport", "Live Events")
        
        lines.append(f'#EXTINF:-1 tvg-id="{tvg_id}" tvg-logo="{tvg_logo}" group-title="{group_title}",{key}')
        lines.append(f"#EXTVLCOPT:http-referrer={REFERER}")
        lines.append(f"#EXTVLCOPT:http-origin={ORIGIN}")
        lines.append(f"#EXTVLCOPT:http-user-agent={USER_AGENTS['vlc']}")
        lines.append(url)
        lines.append("")
        count += 1

    with open(output, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    log.info(f"Generated {output} with {count} events")
    return count


def generate_tivimate_playlist(data: dict, output="strtp_tivimate.m3u8") -> int:
    """Generate TiviMate-compatible playlist with pipe format"""
    ua = urllib.parse.quote(USER_AGENTS['tivimate'], safe="")
    lines = ["#EXTM3U"]
    lines.append(f"# Playlist generated by STRTP Scraper - {Time.clean(Time.now()).strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")
    count = 0

    for key, entry in sorted(data.items()):
        url = entry.get("url")
        if not url:
            continue

        tvg_id = entry.get("id", "Live.Event.us")
        tvg_logo = entry.get("logo", "https://i.gyazo.com/4a5e9fa2525808ee4b65002b56d3450e.png")
        group_title = entry.get("sport", "Live Events")
        
        lines.append(f'#EXTINF:-1 tvg-id="{tvg_id}" tvg-logo="{tvg_logo}" group-title="{group_title}",{key}')
        lines.append(f"{url}|referer={REFERER}|origin={ORIGIN}|user-agent={ua}")
        lines.append("")
        count += 1

    with open(output, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    log.info(f"Generated {output} with {count} events")
    return count


async def process_event(url: str, url_num: int) -> str | None:
    """Process event URL to extract M3U8 stream"""
    try:
        if not (event_data := await network.request(url, log=log)):
            log.warning(f"URL {url_num}) Failed to load url.")
            return None

        digit_func_ptrn = re.compile(r"{return\s+(\d*);}", re.I)

        if not (digit_list := digit_func_ptrn.findall(event_data.text)):
            log.warning(f"URL {url_num}) Unable to decode url - no digit function found.")
            return None

        embed_list_ptrn = re.compile(r"\w*=\[\[(.*)\]\];")

        if not (embed_list := embed_list_ptrn.search(event_data.text)):
            log.warning(f"URL {url_num}) Unable to decode url - no embed list found.")
            return None

        embed_list_str = embed_list[0].split("=", 1)[-1].strip(";")

        try:
            embed_list: list[tuple[int, str]] = ast.literal_eval(embed_list_str)
        except Exception as e:
            log.warning(f"URL {url_num}) Failed to parse embed list: {e}")
            return None

        embed_list.sort(key=lambda i: i[0])

        # Decode the M3U8 URL
        m3u8_parts = []
        for _, v in embed_list:
            try:
                decoded = base64.b64decode(v).decode("utf-8")
                digits = "".join(c for c in decoded if c.isdigit())
                if digits:
                    value = int(digits) - sum(map(int, digit_list))
                    m3u8_parts.append(chr(value))
            except Exception as e:
                log.debug(f"Error decoding part: {e}")
                continue

        m3u8 = "".join(m3u8_parts)

        if not m3u8:
            log.warning(f"URL {url_num}) Decoded empty M3U8")
            return None

        log.info(f"URL {url_num}) Captured M3U8")

        # Remove ip parameter and convert to mono stream format
        m3u8 = remove_ip_param(m3u8)
        
        # Convert to mono.m3u8 format with working token
        if "index.m3u8" in m3u8:
            m3u8 = convert_to_mono_stream(m3u8)
        
        return m3u8
        
    except Exception as e:
        log.error(f"URL {url_num}) Error processing event: {e}")
        return None


async def fetch_api_data() -> list[dict] | None:
    """Fetch API data with retries and fallback"""
    # Try all possible API endpoints
    for api_url in API_ENDPOINTS:
        try:
            log.info(f"Trying API: {api_url}")
            if response := await network.request(api_url, log=log):
                try:
                    data = response.json()
                    if data and isinstance(data, list):
                        log.info(f"Successfully fetched {len(data)} events from {api_url}")
                        return data
                except Exception as e:
                    log.debug(f"Failed to parse response from {api_url}: {e}")
                    continue
        except Exception as e:
            log.debug(f"Failed to fetch from {api_url}: {e}")
            continue
    
    # If no API endpoint worked, try to load from cache
    log.info("Attempting to load from cache...")
    cached_data = API_FILE.load(per_entry=False, index=-1)
    if cached_data and isinstance(cached_data, list) and len(cached_data) > 1:
        log.info(f"Using cached data with {len(cached_data) - 1} events")
        # Remove timestamp entry and filter out non-event entries
        events = [e for e in cached_data if isinstance(e, dict) and e.get("title")]
        if events:
            return events
    
    # If still no data, create sample data to keep the script functional
    log.warning("No API data available. Using empty event list.")
    return []


async def get_events(cached_keys: list[str]) -> list[dict[str, str]]:
    """Get events from API"""
    now = Time.clean(Time.now())

    # Try to fetch fresh data
    api_data = await fetch_api_data()
    
    if api_data:
        # Update cache with fresh data if we got any
        cache_data = [{"timestamp": now.timestamp()}]
        cache_data.extend(api_data)
        API_FILE.write(cache_data)
    else:
        log.info("No API data available, checking cache for existing events...")
        # Try to get events from cache directly
        cached_data = CACHE_FILE.load() or {}
        if cached_data:
            # Return events from cache to maintain functionality
            events = []
            for key, entry in cached_data.items():
                if entry.get("url") and not key in cached_keys:
                    # Extract sport from the key
                    sport_match = re.search(r'\[(.*?)\]', key)
                    sport = sport_match.group(1) if sport_match else "Live Events"
                    event_name = key.split(']')[1].split('(')[0].strip()
                    events.append({
                        "sport": sport,
                        "event": event_name,
                        "link": entry.get("link", "")
                    })
            log.info(f"Loaded {len(events)} events from cache")
            return events
        return []

    events = []
    for event in api_data:
        name = event.get("title")
        link = event.get("link")
        
        # Try alternative field names
        if not link:
            link = event.get("url", event.get("stream_url"))
        if not name:
            name = event.get("name", event.get("event_name"))

        if not (name and link):
            continue

        sport = event.get("category", event.get("sport", "Live Events"))
        
        # Map sport names to proper group titles
        sport_mapping = {
            "Fútbol": "Soccer",
            "Soccer": "Soccer",
            "NBA": "NBA",
            "NFL": "NFL",
            "MLB": "MLB",
            "NHL": "NHL",
            "UFC": "UFC",
            "Boxeo": "BOXING",
            "Boxing": "BOXING",
            "Tenis": "TENNIS",
            "Tennis": "TENNIS",
            "MotoGP": "RACE",
            "Formula 1": "RACE",
            "F1": "RACE"
        }
        
        sport = sport_mapping.get(sport, sport)
        
        if sport == "Other" or not sport:
            sport = "Live Events"

        key = f"[{sport}] {name} ({TAG})"
        
        if key in cached_keys:
            continue

        events.append(
            {
                "sport": sport,
                "event": name,
                "link": link,
            }
        )

    log.info(f"Found {len(events)} new events")
    return events


async def scrape() -> None:
    """Main scraping function"""
    cached_urls = CACHE_FILE.load() or {}

    valid_urls = {k: v for k, v in cached_urls.items() if v.get("url")}
    valid_count = cached_count = len(valid_urls)

    urls.update(valid_urls)

    log.info(f"Loaded {cached_count} event(s) from cache")

    log.info('Scraping from "https://streamtpnew.com"')

    events = await get_events(cached_urls.keys())
    
    if events:
        log.info(f"Processing {len(events)} URL(s)")

        now = Time.clean(Time.now())

        for i, ev in enumerate(events, start=1):
            handler = partial(
                process_event,
                url=(link := ev["link"]),
                url_num=i,
            )

            url = await network.safe_process(
                handler,
                url_num=i,
                semaphore=network.HTTP_S,
                log=log,
            )

            if not url:
                log.warning(f"Event {i}) Failed to extract URL: {ev['event']}")
                continue

            sport, event = ev["sport"], ev["event"]

            key = f"[{sport}] {event} ({TAG})"

            tvg_id, logo = leagues.get_tvg_info(sport, event)

            entry = {
                "url": url,
                "logo": logo,
                "base": link,
                "timestamp": now.timestamp(),
                "id": tvg_id or "Live.Event.us",
                "link": link,
                "sport": sport,
            }

            cached_urls[key] = entry
            urls[key] = entry
            valid_count += 1
            
            log.info(f"Event {i}) ✓ Captured: {event}")

        log.info(f"Collected and cached {valid_count - cached_count} new event(s)")

    else:
        log.info("No events to process, using cached events if available")
        # Keep existing cached events if no new events found

    # Save cache
    CACHE_FILE.write(cached_urls)
    
    # Generate playlists only with valid URLs
    valid_events = {k: v for k, v in urls.items() if v.get("url")}
    
    if valid_events:
        vlc_count = generate_vlc_playlist(valid_events)
        tivimate_count = generate_tivimate_playlist(valid_events)
        log.info(f"Final playlist size: {len(valid_events)} events")
        log.info(f"Total written: {vlc_count + tivimate_count}")
    else:
        log.warning("No valid events to generate playlists")
        # Create empty playlists to avoid errors
        with open("strtp_vlc.m3u8", "w") as f:
            f.write("#EXTM3U\n# No events available\n")
        with open("strtp_tivimate.m3u8", "w") as f:
            f.write("#EXTM3U\n# No events available\n")


async def main() -> None:
    """Main entry point"""
    log.info("Starting STRTP updater")
    await scrape()
    log.info("STRTP updater completed")


def run() -> None:
    """Run the updater"""
    import asyncio
    asyncio.run(main())


if __name__ == "__main__":
    run()
